"""Add generation column for soft reset

Revision ID: 9d850b4cdd5a
Revises: d47947656147
Create Date: 2026-08-25 09:52:41.983094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d850b4cdd5a'
down_revision: Union[str, Sequence[str], None] = 'd47947656147'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('generation', sa.Integer(), nullable=True))
    op.add_column('sessions', sa.Column('generation', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'generation')
    op.drop_column('messages', 'generation')
    # ### end Alembic commands ###
